spring.application.name=TechShop
server.port=8083
# Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

# Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

# En desarrollo el "cache" del servidor (false), en producción "true"
spring.thymeleaf.cache=false
spring.datasource.url=jdbc:mysql://localhost:3306/techshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

firebase.bucket.name=techshop-ff6aa-firebase-storage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=C:/Projects/Portafolio_NatalyScholz/src/main/resources/firebase/techshop-ff6aa-firebase-adminsdk-fbsvc-c7e68f2f81.json